name: Rust-codecov

on:
    push:
      branches:
        - master
    pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --lib --out xml
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
            token:                ${{secrets.CODECOV_KEY}}
            fail_ci_if_error:     true