name: Rust-codecov

on:
    push:
      branches:
        - master
    pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate code coverage
        uses: dtolnay/rust-toolchain@stable
      - run: cargo clean && cargo install cargo-tarpaulin
      - run: cargo tarpaulin --verbose --exclude-files benches/* --out xml
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v3
        with:
            token:                ${{secrets.CODECOV_KEY}}
            fail_ci_if_error:     true